import { useState } from "react";
import { api } from "../api.js";
import { setStudentSession } from "../auth.js";

export function StudentLogin() {
  const [studentId, setStudentId] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function onSubmit(e) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const res = await api("/api/student/login", { method: "POST", body: { studentId } });
      setStudentSession({ token: res.token, student: { studentId: res.student.studentId, fullName: res.student.fullName } });
    } catch (err) {
      setError(err.message || "Login failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="card">
      <h2>Student Login</h2>
      <form onSubmit={onSubmit} className="form">
        <label>
          Student ID (8 characters)
          <input value={studentId} onChange={(e) => setStudentId(e.target.value.toUpperCase())} maxLength={8} />
        </label>
        {error ? <div className="error">{error}</div> : null}
        <button className="button" disabled={loading}>
          {loading ? "Signing in..." : "Sign in"}
        </button>
      </form>
      <p className="muted">Your Student ID is generated by the admin during enrollment.</p>
    </div>
  );
}

